import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import type { TrackCategory } from "../src/types";

/**
 * Committed catalogue of every track *layout* (config) id seen in an archived
 * season, mapping it to its surface. Sourced from the iRacing Data API's
 * `/data/track/get`, which reports `category` per layout.
 *
 * Regenerated by `npm run fetch-track-categories`, and refreshed as a side
 * effect of `fetch-data` / `fetch-prelim` (see `updateTrackCategoryCatalogue`).
 * Always merged, never replaced outright: a layout the live API stops listing
 * (long since rotated out) must keep the category recorded for it here, since
 * it still appears in old archives.
 */
export interface TrackCategoryEntry {
  category: TrackCategory;
  /** For human readability only — not consumed by the compute logic. */
  name?: string;
  config?: string;
}

export type TrackCategoryCatalogue = Record<string, TrackCategoryEntry>;

/** Shape of one entry in the API's `/data/track/get` response, as fetched. */
export interface RawTrackLayout {
  track_id: number;
  track_name: string;
  config_name?: string;
  category?: string;
}

const KNOWN_CATEGORIES = new Set(["road", "oval", "dirt_road", "dirt_oval"]);

function isTrackCategory(value: string): value is TrackCategory {
  return KNOWN_CATEGORIES.has(value);
}

/** Build a catalogue fragment from a live `/data/track/get` response. */
export function buildTrackCategoryCatalogue(tracks: RawTrackLayout[]): TrackCategoryCatalogue {
  const catalogue: TrackCategoryCatalogue = {};
  for (const track of tracks) {
    if (!track.category || !isTrackCategory(track.category)) {
      console.warn(
        `Skipping track ${track.track_id} (${track.track_name}): unrecognised category ` +
          `"${track.category}"`,
      );
      continue;
    }
    catalogue[String(track.track_id)] = {
      category: track.category,
      name: track.track_name,
      ...(track.config_name ? { config: track.config_name } : {}),
    };
  }
  return catalogue;
}

/**
 * Merge a freshly-fetched catalogue over an existing one. Fresh entries win
 * on id conflicts (categories don't change, but names occasionally do); ids
 * only present in `existing` are always kept, since the live API only lists
 * layouts currently in rotation.
 */
export function mergeTrackCategoryCatalogues(
  existing: TrackCategoryCatalogue,
  fresh: TrackCategoryCatalogue,
): TrackCategoryCatalogue {
  return { ...existing, ...fresh };
}

/** Read the committed catalogue, or an empty one if it doesn't exist yet. */
export function readTrackCategoryCatalogue(path: string): TrackCategoryCatalogue {
  try {
    return JSON.parse(readFileSync(path, "utf8")) as TrackCategoryCatalogue;
  } catch {
    return {};
  }
}

/** Write the catalogue, keys sorted numerically for a stable, reviewable diff. */
export function writeTrackCategoryCatalogue(path: string, catalogue: TrackCategoryCatalogue): void {
  const sorted: TrackCategoryCatalogue = {};
  for (const id of Object.keys(catalogue).sort((a, b) => Number(a) - Number(b))) {
    sorted[id] = catalogue[id];
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(sorted, null, 2) + "\n");
}

/**
 * Read the committed catalogue at `path`, merge in `tracks` from a live
 * `/data/track/get` response, write the result back, and return it. Shared by
 * `fetch-schedule.ts`, `fetch-prelim.ts` and the standalone
 * `fetch-track-categories.ts` so every path that already has fresh track data
 * keeps the catalogue current without a redundant API call.
 */
export function updateTrackCategoryCatalogue(
  path: string,
  tracks: RawTrackLayout[],
): TrackCategoryCatalogue {
  const existing = readTrackCategoryCatalogue(path);
  const fresh = buildTrackCategoryCatalogue(tracks);
  const merged = mergeTrackCategoryCatalogues(existing, fresh);
  writeTrackCategoryCatalogue(path, merged);
  console.log(
    `  Track categories: ${Object.keys(merged).length} known ` +
      `(${Object.keys(fresh).length} from this fetch, ${Object.keys(existing).length} previously known)`,
  );
  return merged;
}
